# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: build

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest, r: 'release', rtools: ''}
          - {os: windows-latest, r: 'devel', rtools: '42'}
          - {os: windows-latest, r: 'release', rtools: '42'}
          - {os: windows-latest, r: 'oldrel', rtools: '40'}
          - {os: ubuntu-latest, r: 'release', rtools: ''}
          - {os: ubuntu-latest, r: 'oldrel', rtools: ''}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      NOT_CRAN: true


    steps:
      - uses: actions/checkout@v2
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/build
        with:
          os: matrix.config.os
          r: matrix.config.r
          rtools: matrix.config.rtools
