# Install the requirements for lint and create the caches
on:
  workflow_dispatch

name: lint create cache

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          extra-packages: any::lintr, local::., stan-dev/cmdstanr
          needs: lint

      - uses: ./.github/actions/cmdstanr_cached
        with:
          os: ${{ matrix.config.os }}
          r: ${{ matrix.config.r }}
          rtools: ${{ matrix.config.rtools }}

