# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest, r: 'release', rtools: ''}
          - {os: windows-latest, r: 'devel', rtools: '42'}
          - {os: windows-latest, r: 'release', rtools: '42'}
          - {os: windows-latest, r: 'oldrel', rtools: '40'}
          - {os: ubuntu-latest, r: 'release', rtools: ''}
          - {os: ubuntu-latest, r: 'oldrel', rtools: ''}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      NOT_CRAN: true


    steps:
      - uses: actions/checkout@v2
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Cache Variables
        run: |
          echo "CMDSTANR_PATH=${HOME}/.cmdstanr" >> $GITHUB_ENV
        shell: bash
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true
          rtools-version: '42'

      # packages that are needed for R CMD CHECK
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 3
          extra-packages: |
            stan-dev/cmdstanr
            rcmdcheck
            checkmate
            jsonlite
            posterior
            processx
            R6
            BH
            RcppEigen
            StanHeaders
            RcppParallel
            withr
            testthat
            rmarkdown
            knitr
            any::XML
            any::textshaping

      - name: Cache CmdStan
        uses: actions/cache@v2
        with:
          path: ${{env.CMDSTAN_PATH}}
          key: CmdStan-${{runner.os}}
      - name: Install CmdStanR
        run: |
          cmdstanr::check_cmdstan_toolchain(fix = TRUE)
          cmdstanr::install_cmdstan(cores = parallel::detectCores())
        shell: Rscript {0}
      - name: Install Development RStan on Windows
        if: runner.os == 'Windows'
        run: |
          Sys.setenv(MAKEFLAGS=paste0("-j",parallel::detectCores()))
          install.packages(c("StanHeaders", "rstan"), repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
        shell: Rscript {0}

      - uses: r-lib/actions/check-r-package@v2
        with:
          build_args: 'c("--no-manual", "--no-build-vignettes")'
          args: 'c("--no-manual", "--as-cran", "--ignore-vignettes")'
