name: R

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  models:
    name: R Tests
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {os: ubuntu-latest,     r: 'release'}
          - {os: ubuntu-latest,     r: 'oldrel'}
          - {os: macos-latest,       r: 'release'}
          - {os: macos-latest,       r: 'oldrel'}
          - {os: windows-latest,   r: 'release'}
      fail-fast: false
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      _R_CHECK_TESTS_NLINES_: 0
    steps:
      - name: Checkout github
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up R ${{ matrix.config.r }}
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-tinytex@v1

      - run: tlmgr --version

      - uses: r-lib/actions/setup-pandoc@master
